/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author ANIL VATS
 */
import java.applet.*;
import java.awt.*;
import java.awt.event.*;
/*
<applet code="ChoiceDemo" width=300 height=180>
</applet>
*/
public class ChoiceAndList extends Applet implements ItemListener,ActionListener{
Choice os, browser;
String msg = "";
List os1, browser1;
String msg1 = "";

public void init() {
os = new Choice();
browser = new Choice();

os1 = new List(4, true);
browser1 = new List(4, false);


// add items to os list
os.add("Windows");
os.add("Android");
os.add("Solaris");
os.add("Mac OS");


// add items to os List Objects
os1.add("Windows");
os1.add("Android");
os1.add("Solaris");
os1.add("Mac OS");

// add items to os List Objects 
// add items to browser list
browser.add("Internet Explorer");
browser.add("Firefox");
browser.add("Chrome");

browser1.add("Internet Explorer1");
browser1.add("Firefox1");
browser1.add("Chrome1");
// add choice lists to window
add(os);
add(browser);


browser.select(1);
//  adding the list objects 
add(os1);
add(browser1);
// register to receive item events
os.addItemListener(this);
browser.addItemListener(this);

// register to receive action events for List Objects 
os1.addActionListener(this);
browser1.addActionListener(this);
}
public void itemStateChanged(ItemEvent ie) {
repaint();
}
public void actionPerformed(ActionEvent ae) {
repaint();
}
// Display current selections.
public void paint(Graphics g) {
int idx[];
msg = "Current OS: ";
msg += os.getSelectedItem();


msg1 = "Current OS: ";
g.drawString(msg, 6, 120);
msg = "Current Browser: ";
msg += browser.getSelectedItem();
g.drawString(msg, 6, 140);

msg1 = "Current OS: ";

idx = os1.getSelectedIndexes();
for(int i=0; i<idx.length; i++)
msg1 += os1.getItem(idx[i]) + " ";
g.drawString(msg1, 10, 160);
msg1 = "Current Browser: ";
msg1 += browser1.getSelectedItem();
g.drawString(msg1, 10, 180);
}
}


    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
